// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AllDriversStat struct {
	Position                 int64
	MeetingKey               int32
	SessionKey               int32
	DriverNumber             int32
	LapNumber                int32
	Interval                 float64
	PredictionLapsToOvertake pgtype.Int4
	LastLapDuration          float64
	Pitsops                  pgtype.Int8
	LastPitLap               interface{}
}

type CompleteLap struct {
	MeetingKey     int32
	SessionKey     int32
	DriverNumber   int32
	DateStart      pgtype.Timestamptz
	LapDuration    float64
	LapNumber      int32
	SectorDuration []float64
	InfoTime       pgtype.Timestamptz
	IsPitOutLap    bool
	UpdatedAt      pgtype.Timestamptz
}

type Driver struct {
	DriverNumber int64
	TeamKey      pgtype.Int4
	FullName     string
	Abbreviation string
	Country      pgtype.Text
	DateOfBirth  pgtype.Date
	Description  string
}

type DriverPositionsWithIntervalsAndLastLap struct {
	Position                 int64
	MeetingKey               int32
	SessionKey               int32
	DriverNumber             int32
	LapNumber                int32
	Interval                 float64
	PredictionLapsToOvertake pgtype.Int4
	LastLapDuration          float64
}

type DriversInterval struct {
	MeetingKey               int32
	SessionKey               int32
	DriverNumber             int32
	Interval                 float64
	PredictionLapsToOvertake pgtype.Int4
}

type DriversPositionsWithInterval struct {
	Position                 int64
	MeetingKey               int32
	SessionKey               int32
	DriverNumber             int32
	LapNumber                int32
	Interval                 float64
	PredictionLapsToOvertake pgtype.Int4
}

type DriversStat struct {
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}

type DriversStatsWithPosition struct {
	Position         int64
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}

type FullDriverDatum struct {
	Position                 int64
	MeetingKey               int32
	SessionKey               int32
	DriverNumber             int32
	LapNumber                int32
	Interval                 float64
	PredictionLapsToOvertake pgtype.Int4
	LastLapDuration          float64
	Pitsops                  pgtype.Int8
	LastPitLap               interface{}
	FullName                 string
	Abbreviation             string
	Name                     string
	Color                    pgtype.Text
}

type Lap struct {
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}

type Meeting struct {
	MeetingKey    int64
	Name          string
	Description   string
	Circuit       string
	Location      string
	StartDate     pgtype.Timestamptz
	EndDate       pgtype.Timestamptz
	Year          int32
	DashboardLink pgtype.Text
}

type Team struct {
	TeamKey     int64
	Name        string
	Description string
	Country     pgtype.Text
	Color       pgtype.Text
}
