// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompleteLap struct {
	MeetingKey     int32
	SessionKey     int32
	DriverNumber   int32
	DateStart      pgtype.Timestamptz
	LapDuration    float64
	LapNumber      int32
	SectorDuration []float64
	InfoTime       pgtype.Timestamptz
	IsPitOutLap    bool
	UpdatedAt      pgtype.Timestamptz
}

type DriversStat struct {
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}

type DriversStatsWithPosition struct {
	Position         int64
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}

type Lap struct {
	MeetingKey       int32
	SessionKey       int32
	DriverNumber     int32
	CompletedSectors int32
	DateStart        pgtype.Timestamptz
	LapDuration      float64
	LapNumber        int32
	SectorDuration   []float64
	DateEnd          pgtype.Timestamptz
	InfoTime         pgtype.Timestamptz
	IsPitOutLap      bool
	UpdatedAt        pgtype.Timestamptz
}
