// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompleteLap struct {
	MeetingKey     int32
	SessionKey     int32
	DriverNumber   int32
	DateStart      pgtype.Timestamptz
	LapDuration    float64
	LapNumber      int32
	SectorDuration []float64
	InfoTime       pgtype.Timestamptz
	IsPitOutLap    bool
	UpdatedAt      pgtype.Timestamptz
}

type DriversStat struct {
	MeetingKey   int32
	SessionKey   int32
	DriverNumber int32
	DateStart    pgtype.Timestamptz
	DateEnd      pgtype.Timestamptz
	LapDuration  float64
	Sectors      int32
	LapNumber    int32
}

type DriversStatsWithPosition struct {
	Position     int64
	MeetingKey   int32
	SessionKey   int32
	DriverNumber int32
	DateStart    pgtype.Timestamptz
	DateEnd      pgtype.Timestamptz
	LapDuration  float64
	Sectors      int32
	LapNumber    int32
}

type Lap struct {
	MeetingKey     int32
	SessionKey     int32
	DriverNumber   int32
	DateStart      pgtype.Timestamptz
	LapDuration    float64
	LapNumber      int32
	SectorDuration []float64
	InfoTime       pgtype.Timestamptz
	IsPitOutLap    bool
	UpdatedAt      pgtype.Timestamptz
}
