// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetLap(ctx context.Context, arg GetLapParams) (Lap, error)
	MoveCompleteLap(ctx context.Context, arg MoveCompleteLapParams) error
	UpsertLap(ctx context.Context, arg UpsertLapParams) error
}

var _ Querier = (*Queries)(nil)
