{
 "title": "Формула-1 Гран-При Венгрии 2024",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время последнего круга",
   "type": "table",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(current_lap_time_seconds{meeting=\"1241\", session=\"9566\"}[1m])",
     "legendFormat": "{{driver_number}}",
     "rawSql": "select position as \"Позиция\", driver_number as \"Номер гонщика\", lap_number as \"Текущий круг\", last_lap_duration as \"Последнее время круга\", \"interval\" as \"Интервал (сек)\", prediction_laps_to_overtake \"Обгон (прогноз)\", pitsops as \"Осстановки\", last_pit_lap as \"Круг последней остановки\" \r\nfrom full_driver_data\r\nWHERE meeting_key = 1241 and session_key = 9566 \r\nORDER BY position;"
    }
   ]
  },
  {
   "title": "Круги гонщиков",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(current_lap_time_seconds{meeting=\"1241\", session=\"9566\"}[$__interval])",
     "legendFormat": "{{driver_number}}"
    }
   ]
  },
  {
   "title": "Текущий средний темп гонщиков на отрезке",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "segment_pace_seconds{meeting=\"1241\", session=\"9566\"}",
     "legendFormat": "{{driver_number}}          |"
    }
   ]
  },
  {
   "title": "Текущий средний темп гонщиков в гонке",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_lap_time_seconds{meeting=\"1241\", session=\"9566\"}",
     "legendFormat": "{{driver_number}}          |"
    }
   ]
  }
 ]
}