// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Lap struct {
	ID              int64
	MeetingKey      int32
	SessionKey      int32
	DriverNumber    pgtype.Int4
	I1Speed         pgtype.Int4
	I2Speed         pgtype.Int4
	StSpeed         pgtype.Int4
	DateStart       pgtype.Timestamp
	LapDuration     pgtype.Float8
	IsPitOutLap     pgtype.Bool
	DurationSector1 pgtype.Float8
	DurationSector2 pgtype.Float8
	DurationSector3 pgtype.Float8
	SegmentsSector1 []int32
	SegmentsSector2 []int32
	SegmentsSector3 []int32
	LapNumber       int32
}
